# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisatie',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('Cluster', models.CharField(max_length=255, null=True)),
                ('Organisatie', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'organisatie',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='Indicatiebedrag',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='project',
            name='Maximumbedrag',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
