# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171004_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Organisatie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisatie_project', to='app.Organisatie'),
        ),
    ]
