version: "3.0"
services:
  database:
    image: amsterdam/postgres
    ports:
      - "5402:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: ibprojecten
      POSTGRES_USER: ibprojecten

  web:
    build: ./web
    ports:
      - "8112:8000"
    links:
      - database:database
    environment:
      DB_NAME: ibprojecten
      DB_PASSWORD: insecure
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "ibprojecten.wsgi:application"
      UWSGI_PROCESSES: 4
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/static=/static"