# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 18:08
from __future__ import unicode_literals

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import ibprojecten.api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('Voornaam', models.CharField(max_length=255, null=True)),
                ('Achternaam', models.CharField(max_length=255, null=True)),
                ('Email', models.CharField(max_length=128, null=True)),
                ('Telefoon', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Organisatie',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('Cluster', models.CharField(max_length=255, null=True)),
                ('Organisatie', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'organisatie',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pjid', models.AutoField(primary_key=True, serialize=False)),
                ('Projectnaam', models.CharField(max_length=255)),
                ('Intakedatum', models.DateField(default=datetime.datetime.now)),
                ('startdatum', models.DateField(default=datetime.datetime.now)),
                ('einddatum', models.DateField(default=datetime.datetime.now)),
                ('Plangebied', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
                ('Planningsnummer', models.CharField(max_length=18, null=True)),
                ('Indicatiebedrag', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('Maximumbedrag', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('Vervolgafspraken', models.TextField(blank=True, null=True)),
                ('Accounthouder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountant_project', to='ibprojecten.Employee')),
                ('Ambtelijkopdrachtgever', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officialclient_project', to='ibprojecten.Employee')),
                ('Bestuurlijkopdrachtgever', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrativeclient_project', to='ibprojecten.Employee')),
                ('Deelprojectleider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_project', to='ibprojecten.Employee')),
                ('Opdrachtverantwoordelijke', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maincontractor_project', to='ibprojecten.Employee')),
                ('Organisatie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisatie_project', to='ibprojecten.Organisatie')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='ProjectPlan',
            fields=[
                ('pp_id', models.AutoField(primary_key=True, serialize=False)),
                ('Projectplan', models.FileField(blank=True, upload_to=ibprojecten.api.models.project_directory_path)),
                ('Aanleiding', models.CharField(blank=True, max_length=2000, null=True)),
                ('Doel', models.CharField(blank=True, max_length=2000, null=True)),
                ('Resultaat', models.CharField(blank=True, max_length=2000, null=True)),
                ('Afbakening', models.CharField(blank=True, max_length=2000, null=True)),
                ('Project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectplan_project_set', to='ibprojecten.Project')),
            ],
            options={
                'db_table': 'projectplan',
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('Projectype', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'projecttype',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('Rol', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Werkorder',
            fields=[
                ('werkorder_id', models.AutoField(primary_key=True, serialize=False)),
                ('Werkordernaam', models.CharField(max_length=255, null=True)),
                ('Planningsnummer', models.CharField(max_length=18, null=True)),
                ('Boekingscombinatie', models.CharField(max_length=18, null=True)),
                ('Project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='werkorder_project_set', to='ibprojecten.Project')),
            ],
            options={
                'db_table': 'werkorder',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='Projecttype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projecttype_project', to='ibprojecten.ProjectType'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collegue_role', to='ibprojecten.Rol'),
        ),
    ]
