# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibprojecten', '0002_auto_20171006_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Accountant',
            new_name='Account_houder',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='OfficalClient',
            new_name='Ambtelijk_opdrachtgever',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='AdministrativeClient',
            new_name='Bestuurlijk_opdrachtgever',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='SubContractor',
            new_name='Deel_projectleider',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='MainContractor',
            new_name='Opdracht_verantwoordelijke',
        ),
    ]
