# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibprojecten', '0003_auto_20171007_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ZoekeenCollegaUrl',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
