# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibprojecten', '0004_employee_zoekeencollegaurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ZoekeenCollegaUrl',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
