# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibprojecten', '0005_auto_20171009_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Projectnaam',
            new_name='Locatie',
        ),
    ]
