# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibprojecten', '0007_werkorder_werkorderplangebied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Projecttype',
        ),
        migrations.AddField(
            model_name='projecttype',
            name='Project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projecttype_project_set', to='ibprojecten.Project'),
        ),
    ]
