# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibprojecten', '0008_auto_20171011_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttype',
            name='Project',
        ),
    ]
