# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibprojecten', '0009_remove_projecttype_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Projecttype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projecttype_project', to='ibprojecten.ProjectType'),
        ),
    ]
