# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibprojecten', '0010_project_projecttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='werkorder',
            name='WerkorderPlangebied',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Projecttype',
        ),
        migrations.AddField(
            model_name='project',
            name='Projecttype',
            field=models.ManyToManyField(to='ibprojecten.ProjectType'),
        ),
    ]
