# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibprojecten', '0012_auto_20171011_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Projecttype',
            field=models.ManyToManyField(related_name='project_type_project', to='ibprojecten.ProjectType'),
        ),
    ]
