# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibprojecten', '0013_auto_20171011_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Planningsnummer',
            new_name='Timetellnummer',
        ),
        migrations.RenameField(
            model_name='werkorder',
            old_name='Planningsnummer',
            new_name='Timetellnummer',
        ),
    ]
