# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 12:55
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibprojecten', '0015_werkorder_werkorderplangebied'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoofdType',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('Hoofdtype', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'hoofdtype',
            },
        ),
        migrations.CreateModel(
            name='WerkorderType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('Werkordertype', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'werkordertype',
            },
        ),
        migrations.RenameField(
            model_name='projecttype',
            old_name='Projectype',
            new_name='Aard',
        ),
        migrations.AddField(
            model_name='projecttype',
            name='Hoofdtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoofdtype_aard', to='ibprojecten.Rol'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Indicatiebedrag',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='project',
            name='Maximumbedrag',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='project',
            name='Opdracht_verantwoordelijke',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maincontractor_project', to='ibprojecten.Employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Timetellnummer',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='werkorder',
            name='Boekingscombinatie',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='werkorder',
            name='Timetellnummer',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='werkorder',
            name='WerkorderPlangebied',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='werkorder',
            name='Werkordernaam',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='werkorder',
            name='Werkordertype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='werkordertype_werkorder_set', to='ibprojecten.WerkorderType'),
        ),
    ]
