# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibprojecten', '0016_auto_20171013_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttype',
            name='Hoofdtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoofdtype_aard', to='ibprojecten.HoofdType'),
        ),
    ]
