# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibprojecten', '0017_auto_20171013_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoofdtype',
            name='HoofdtypeAfkorting',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
