# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 13:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibprojecten', '0018_hoofdtype_hoofdtypeafkorting'),
    ]

    operations = [
        migrations.AddField(
            model_name='werkorder',
            name='einddatum',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='werkorder',
            name='startdatum',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
