# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibprojecten', '0019_auto_20171013_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='werkorder',
            name='Werkordertype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='werkordertype_werkorder_set', to='ibprojecten.WerkorderType'),
        ),
    ]
