# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibprojecten', '0020_auto_20171013_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='werkorder',
            old_name='Werkordernaam',
            new_name='TimetellNaam',
        ),
    ]
