# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibprojecten', '0021_auto_20171013_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Organisatie',
            new_name='Organisatie_opdrachtgever',
        ),
    ]
