# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibprojecten', '0022_auto_20171013_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Projecttype',
        ),
        migrations.AddField(
            model_name='project',
            name='Aard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_type_project', to='ibprojecten.ProjectType'),
        ),
        migrations.AddField(
            model_name='project',
            name='Hoofdtype',
            field=models.ManyToManyField(related_name='aard_project', to='ibprojecten.ProjectType'),
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='Hoofdtype',
        ),
        migrations.AddField(
            model_name='projecttype',
            name='Hoofdtype',
            field=models.ManyToManyField(related_name='hoofdtype_aard', to='ibprojecten.HoofdType'),
        ),
    ]
