# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibprojecten', '0025_auto_20171013_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttype',
            old_name='Aard',
            new_name='Soort',
        ),
    ]
